### PR TITLE
Update README and small fix for reporting higher wattage.

### PR DESCRIPTION
**Pull request by JohanLeirnes**
Added automation for showing todays kWh and the template sensors used to show the data from the automations.

### CODE REVIEW

**Comment by JohanLeirnes** [comment]
Also removed data_[4] from bad if statement as this was causing alot of good packages to be marked as bad.

**Comment by tubalainen** [comment]
SUPER! Thanks!

**Comment by fredrike** [comment]
I get the following from the automations:

```
Update for sensor.kwh_current_month fails
11:26 AM helpers/template.py (ERROR)
...
File "<template>", line 1, in top-level template code                                             
TypeError: unsupported operand type(s) for -: 'float' and 'str'                                     
```

And the `Sparsnäs current month` reports `Unknown`, is there anything that can be added to the automation of Hass?

**Comment by fredrike** [comment]
What about this (under `value_template: >-` of `kwh_current_month`) 😄  (am I doing something wrong or is the assumption ok?)
```jinja
{%  if is_state('states.sensor.sparsnas_template_kwh_sensor_month.state', 'Unknown') %}
  {{(float(states.sensor.sparsnas_energy_consumption_over_time.state) - 
    float(states.sensor.sparsnas_template_kwh_sensor_month.state)) | round(1) }}
{% else %}
  {{float(states.sensor.sparsnas_energy_consumption_over_time.state)  | round(1) }}
{% endif %}
```

**Comment by JohanLeirnes** [comment]
Yes you would get this the first time you start. If you trigger both automations then you will never get the error again.

But the template should be turned around i think.

{%  if is_state('states.sensor.sparsnas_template_kwh_sensor_month.state', 'Unknown') %}
  {{float(states.sensor.sparsnas_energy_consumption_over_time.state)  | round(1) }}
{% else %}
  {{(float(states.sensor.sparsnas_energy_consumption_over_time.state) - 
    float(states.sensor.sparsnas_template_kwh_sensor_month.state)) | round(1) }}
{% endif %}

But as i stated, if one just triggers both the automations once then you will not get this error.

**Comment by tubalainen** [comment]
Hello all!

Can you please make a suggested change, I will commit it :)

Thanks!

**Comment by fredrike** [comment]
I'm not sure but I guess the best solution would be as @bhaap say and trigger the automations once. Perhaps we can create an automation that runs at startup and checks if `states.sensor.sparsnas_template_kwh_sensor_month.state` is set or not. Something like this (but I don't dare to test it). 

```yaml
- data:
      entity_id: automation. automation.sparsnas_monthly_consumption
    service: automation.trigger
  alias: trigger-sparsnas
condition:
  condition: state
  entity_id: sensor.sparsnas_template_kwh_sensor_month
  state: Unknown
  trigger:
  - event: start
    platform: homeassistant
```

I've built a package yaml that I will push later today (or so).

**Comment by fredrike** [comment]
Just noticed that the sparsnas_montly_consumption didn't get triggered last night..

```json
{
  "last_triggered": "2018-01-31T13:12:59.883143+00:00",
  "id": "1516722867362",
  "friendly_name": "Sparsnäs monthly consumption",
  "custom_ui_state_card": "state-card-custom-ui"
}
```

screen shot 2018-02-01 at 8 19 28

Is there an issue with the automations?

**Comment by JohanLeirnes** [comment]
Thats wierd. mine triggered just fine.

```
{
  "last_triggered": "2018-01-31T23:00:01.798585+00:00",
  "friendly_name": "Spara kWh varje månad",
  "hidden": true,
  "custom_ui_state_card": "state-card-custom-ui"
}
```

**Comment by fredrike** [comment]
This is my `packages/sparsnas.yaml`, any ideas?

```yaml
sensor:
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs energy consumption momentary"
    unit_of_measurement: "W"
    value_template: '{{ value_json.Watt | round(1) }}'
    icon: mdi:flash-circle
# Note that the sensor below will be resetted if you remove/reinstall the batteries in the Sparsnäs transmitter
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs energy consumption over time"
    unit_of_measurement: "kWh"
    value_template: '{{ value_json.kWh | round(1) }}'
    hidden: true
    icon: mdi:flash-circle
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs Battery remaining"
    unit_of_measurement: "%"
    value_template: '{{ value_json.battery | round(1) }}'
    hidden: true
    icon: mdi:battery-outline
  - platform: mqtt
    state_topic: "home/sparsnas"
    name: "Sparsnäs Frequency Error"
    unit_of_measurement: "%"
    value_template: '{{ value_json.FreqErr }}'
    hidden: true
    icon: mdi:signal
  - platform: mqtt
    name: "Sparsnäs template kwh sensor day"
    state_topic: "template/kwh/day"
    icon: mdi:flash-circle
    hidden: true
  - platform: mqtt
    name: "Sparsnäs template kwh sensor month"
    state_topic: "template/kwh/month"
    icon: mdi:flash-circle
    hidden: true
  - platform: template
    sensors:
      kwh_current_month:
        friendly_name: "Sparsnäs current month"
        unit_of_measurement: "kWh"
        value_template: >-
          {{ (float(states.sensor.sparsnas_energy_consumption_over_time.state) - float(states.sensor.sparsnas_template_kwh_sensor_month.state)) | round(1) }}
      kwh_today:
        friendly_name: "Sparsnäs current day"
        unit_of_measurement: "kWh"
        value_template: >-
          {{ (float(states.sensor.sparsnas_energy_consumption_over_time.state) - float(states.sensor.sparsnas_template_kwh_sensor_day.state)) | round(1) }}

# Thanks to @bhaap and @naestrom for the monthly and daily automation below
automation:
- action:
  - data:
      payload_template: '{{ states(''sensor.sparsnas_energy_consumption_over_time'')
        }}'
      retain: 'true'
      topic: template/kwh/month
    service: mqtt.publish
  alias: Sparsnäs monthly consumption
  condition:
  - condition: template
    value_template: '{{ now().month() | string == "1" }}'
  - condition: template
    value_template: '{{ now().month() | string == "2" }}'
  - condition: template
    value_template: '{{ now().month() | string == "3" }}'
  - condition: template
    value_template: '{{ now().month() | string == "4" }}'
  - condition: template
    value_template: '{{ now().month() | string == "5" }}'
  - condition: template
    value_template: '{{ now().month() | string == "6" }}'
  - condition: template
    value_template: '{{ now().month() | string == "7" }}'
  - condition: template
    value_template: '{{ now().month() | string == "8" }}'
  - condition: template
    value_template: '{{ now().month() | string == "9" }}'
  - condition: template
    value_template: '{{ now().month() | string == "10" }}'
  - condition: template
    value_template: '{{ now().month() | string == "11" }}'
  - condition: template
    value_template: '{{ now().month() | string == "12" }}'
  id: '1516722867362'
  trigger:
  - at: 00:00:01
    platform: time
- action:
  - data:
      payload_template: "{{ states('sensor.sparsnas_energy_consumption_over_time')}}"
      retain: 'true'
      topic: template/kwh/day
    service: mqtt.publish
  alias: Sparsnäs daily consumption
  condition: []
  id: '1516806539856'
  trigger:
  - at: 00:00:02
    platform: time

group:
  sparsnas:
    name: Energy Consumption
    view: no
    icon: mdi:flash-circle
    entities:
      - sensor.sparsnas_energy_consumption_momentary
      - sensor.sparsnas_energy_consumption_over_time
      - sensor.sparsnas_battery_remaining
      - sensor.sparsnas_frequency_error
      - sensor.kwh_today
      - sensor.kwh_current_month
```

**Comment by JohanLeirnes** [comment]
Yes, change now().month() to now().month

**Comment by JohanLeirnes** [comment]
I've done a PR to fix this in the Readme. 

About the automation its not a bad idea.

This should be correct.

```
action:
  - data:
      entity_id: automation.sparsnas_monthly_consumption
    service: automation.trigger
alias: trigger-sparsnas-if-unknown
condition:
  condition: state
  entity_id: sensor.sparsnas_template_kwh_sensor_month
  state: Unknown
trigger:
  - event: start
    platform: homeassistant
id: '159293779102'
```

**Comment by JohanLeirnes** [comment]
But i think the automation should trigger when sensor.sparsnas_energy_consumption_over_time gets its first value.

like this:
```
action:
  - data:
      entity_id: automation.sparsnas_monthly_consumption
    service: automation.trigger
alias: trigger-sparsnas-if-unknown
condition:
  condition: state
  entity_id: sensor.sparsnas_template_kwh_sensor_month
  state: Unknown
trigger:
  - event: state
    entity_id: sensor.sparsnas_energy_consumption_over_time
    from: 'unknown'
id: '159293779102'
```

**Comment by fredrike** [comment]
And with both monthly and daily?:

```yaml
- action:
    - data:
        entity_id: automation.sparsnas_daily_consumption
      service: automation.trigger
    - data:
        entity_id: automation.sparsnas_monthly_consumption
      service: automation.trigger
  alias: trigger-sparsnas-if-unknown
  condition:
    condition: state
    entity_id: sensor.sparsnas_template_kwh_sensor_month
    state: Unknown
  trigger:
    - event: state
      entity_id: sensor.sparsnas_energy_consumption_over_time
      from: 'unknown'
  id: '159293779102'
```

**Pull request merged**
